name: ledefault artifact

on:
  push:
    branches: ['main']
    tags: ['ledefault@*']
  pull_request:
    branches: ['main']

env:
  REGISTRY: docker.io
  IMAGE_NAME: melchor9000/ledefault
  PUBLISH: ${{ startsWith(github.ref, 'refs/tags/ledefault@') }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Checkout actions
        uses: actions/checkout@v5
        with:
          repository: melchor629/actions
          ref: main
          token: ${{ secrets.PAT_GITHUB }}
          path: ./.github/actions
          fetch-depth: 0

      - name: Setup docker
        uses: ./.github/actions/docker/prepare
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build image
        uses: ./.github/actions/docker/build
        if: ${{ env.PUBLISH == 'false' }}
        with:
          file: ./apps/ledefault/docker/Dockerfile

      - name: Extract version
        uses: ./.github/actions/utils/version
        id: version
        if: ${{ env.PUBLISH == 'true' }}

      - name: Build and push image
        uses: ./.github/actions/docker/push-hub
        if: ${{ env.PUBLISH == 'true' }}
        with:
          file: ./apps/ledefault/docker/Dockerfile
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.version }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ startsWith(github.ref, 'refs/tags/ledefault@') }}
    environment: pi
    steps:
      - name: Checkout actions
        uses: actions/checkout@v5
        with:
          repository: melchor629/actions
          ref: main
          token: ${{ secrets.PAT_GITHUB }}
          path: ./.github/actions
          fetch-depth: 0

      - name: Deploy
        uses: ./.github/actions/deploy/pi
        with:
          project: ledefault
