name: nas-persistance artifact

on:
  push:
    tags: ['nas-persistance@*']

env:
  REGISTRY: docker.io
  IMAGE_NAME: melchor9000/nas-persistance

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Checkout actions
        uses: actions/checkout@v5
        with:
          repository: melchor629/actions
          ref: main
          token: ${{ secrets.PAT_GITHUB }}
          path: ./.github/actions
          fetch-depth: 0

      - name: Setup docker
        uses: ./.github/actions/docker/prepare
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Extract version
        uses: ./.github/actions/utils/version
        id: version

      - name: Build and push image
        uses: ./.github/actions/docker/push-hub
        with:
          file: ./apps/nas-persistance/docker/Dockerfile
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.version }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: pi
    steps:
      - name: Checkout actions
        uses: actions/checkout@v5
        with:
          repository: melchor629/actions
          ref: main
          token: ${{ secrets.PAT_GITHUB }}
          path: ./.github/actions
          fetch-depth: 0

      - name: Deploy
        uses: ./.github/actions/deploy/pi
        with:
          project: nas
